### ISSUE TITLE
Compatibility shims issue with protobuf dependency

### ISSUE THREAD

**Issue by jayhof** [opensnowcat/opensnowcat-enrich#289]
Thank you for all the work in keeping this platform open-source ❤️ 

I'm trying to deploy opensnowcat-enrich on GCP with the pubsub connector and ran into an issue with the version of the protobuf dependency.

Here's the relevant part of the logged error:
```
ERROR com.snowplowanalytics.snowplow.enrich.common.fs2.Enrich - Unexpected error in enrich
com.permutive.pubsub.consumer.grpc.PubsubGoogleConsumer$InternalPubSubError: Internal Java PubSub consumer failed
Caused by: java.lang.IllegalStateException: Expected the service InnerService [FAILED] to be RUNNING, but the service has FAILED
        at com.google.common.util.concurrent.AbstractService.checkCurrentState(AbstractService.java:384)
        at com.google.common.util.concurrent.AbstractService.awaitRunning(AbstractService.java:308)
        at com.google.api.core.AbstractApiService.awaitRunning(AbstractApiService.java:95)
        at com.google.cloud.pubsub.v1.Subscriber.startConnections(Subscriber.java:379)
        at com.google.cloud.pubsub.v1.Subscriber.startStreamingConnections(Subscriber.java:341)
        at com.google.cloud.pubsub.v1.Subscriber.access$1400(Subscriber.java:91)
        at com.google.cloud.pubsub.v1.Subscriber$1.run(Subscriber.java:282)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: com/google/protobuf/GeneratedMessageV3$Builder
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
        at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(Unknown Source)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(Unknown Source)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(Unknown Source)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at com.google.pubsub.v1.StreamingPullRequest.toBuilder(StreamingPullRequest.java:866)
        at com.google.pubsub.v1.StreamingPullRequest.newBuilder(StreamingPullRequest.java:857)
        at com.google.cloud.pubsub.v1.StreamingSubscriberConnection.initialize(StreamingSubscriberConnection.java:237)
        at com.google.cloud.pubsub.v1.StreamingSubscriberConnection.doStart(StreamingSubscriberConnection.java:146)
        at com.google.api.core.AbstractApiService$InnerService.doStart(AbstractApiService.java:147)
        at com.google.common.util.concurrent.AbstractService.startAsync(AbstractService.java:252)
        at com.google.api.core.AbstractApiService.startAsync(AbstractApiService.java:119)
        at com.google.cloud.pubsub.v1.Subscriber.startConnections(Subscriber.java:376)
        ... 4 more
Caused by: java.lang.ClassNotFoundException: com.google.protobuf.GeneratedMessageV3$Builder
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 21 more
```

This issue was introduced with protobuf 4.26.0 and has since been fixed: https://github.com/protocolbuffers/protobuf/commit/df8a11e2666ad2940b0483c00d4aff586315b9a0

I've forked the repo, updated protobuf to version 4.28.3, pushed to my own docker repo, deployed this updated image and was able to verify this fixed the issue.

**Comment by joaolcorreia** [comment]
Hi @jayhof is this fixed?

**Comment by jayhof** [comment]
Hello @joaolcorreia, thanks for looking into the issue. I've built a test image with the latest changes from main and deployed in my test environment on GCP.

While the error from above is now gone, i'm running into the issue that the stream is resetting immediately. Seems the same as described here: https://github.com/opensnowcat/opensnowcat-enrich/pull/290#issuecomment-2531867671

Here's some more DEBUG lvl output (bearer token redacted):
```
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] OUTBOUND HEADERS: streamId=21 headers=GrpcHttp2OutboundHeaders[:authority: pubsub.googleapis.com:443, :path: /google.pubsub.v1.Subscriber/StreamingPull, :method: POST, :scheme: https, content-type: application/grpc, te: trailers, user-agent: Snowplow OSS/enrich (GPN:Snowplow;) grpc-java-netty/1.60.0, x-goog-api-client: gl-java/11.0.24__Debian gapic/1.114.3 gax/2.39.0 grpc/1.60.0, grpc-accept-encoding: gzip, authorization: Bearer ... streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] OUTBOUND DATA: streamId=21 padding=0 endStream=false length=123 bytes=00000000760a4470726f6a656374732f6f76622d6465762d70726a2d646174612d322f737562736372697074696f6e732f6f76622d6465762d70736e2d73632d...
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] INBOUND HEADERS: streamId=21 headers=GrpcHttp2ResponseHeaders[:status: 200, content-disposition: attachment, content-type: application/grpc, date: Fri, 10 Jan 2025 09:51:29 GMT] padding=0 endStream=false
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] INBOUND DATA: streamId=21 padding=0 endStream=false length=7785 bytes=00000023b60ad0160ac4014268597358555a495554635a43476852446b3965497a383149436846455145465a304d324245596643776463584855485551775164...
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] INBOUND DATA: streamId=21 padding=0 endStream=false length=1362 bytes=5c225c222c5c22637561557569645c223a5c2265646563323130382d373532362d343836332d363233612d6338643761343639396135645c227d7d2c7b5c2273...
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] INBOUND DATA: streamId=21 padding=0 endStream=false length=8192 bytes=000000a5610aac160ac4014268597358555a495554635a43476852446b3965497a383149436846455145465a304d324245596643776463584855485551775164...
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] INBOUND DATA: streamId=21 padding=0 endStream=false length=8192 bytes=3333640b7a690000004169676c753a636f6d2e736e6f77706c6f77616e616c79746963732e736e6f77706c6f772f436f6c6c6563746f725061796c6f61642f74...
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] OUTBOUND RST_STREAM: streamId=21 errorCode=8
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] INBOUND DATA: streamId=21 padding=0 endStream=false length=8192 bytes=0000214f726967696e3a2068747470733a2f2f7777772e636869656d67617532342e64650000001a7365632d66657463682d736974653a2063726f73732d7369...
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] OUTBOUND RST_STREAM: streamId=21 errorCode=5
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] INBOUND DATA: streamId=21 padding=0 endStream=false length=8192 bytes=74653a2063726f73732d73697465000000147365632d66657463682d6d6f64653a20636f7273000000157365632d66657463682d646573743a20656d70747900...
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] OUTBOUND RST_STREAM: streamId=21 errorCode=5
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] INBOUND DATA: streamId=21 padding=0 endStream=false length=8192 bytes=6f76626d656469612e64650000000b4163636570743a202a2f2a0000001a7365632d66657463682d736974653a2063726f73732d73697465000000224f726967...
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] OUTBOUND RST_STREAM: streamId=21 errorCode=5
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] INBOUND DATA: streamId=21 padding=0 endStream=false length=1382 bytes=615c223a7b5c2275736572547970655c223a5c225c222c5c22637561557569645c223a5c2236666264636463372d303062302d306533332d343065322d356662...
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] OUTBOUND RST_STREAM: streamId=21 errorCode=5
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] INBOUND DATA: streamId=21 padding=0 endStream=false length=2802 bytes=0000000aed0ae8150ac4014268597358555a495554635a43476852446b3965497a383149436846455145465a304d324245596643776463584855485551775164...
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] OUTBOUND RST_STREAM: streamId=21 errorCode=5
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] INBOUND DATA: streamId=21 padding=0 endStream=false length=8192 bytes=000001aa270add160ac4014268597358555a495554635a43476852446b3965497a383149436846455145465a304d324245596643776463584855485551775164...
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] OUTBOUND RST_STREAM: streamId=21 errorCode=5
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] INBOUND DATA: streamId=21 padding=0 endStream=false length=8192 bytes=746f3a20687474707300000016436f6e6e656374696f6e3a204b6565702d416c697665000000106170706c69636174696f6e2f6a736f6e0b0168000000106170...
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] OUTBOUND RST_STREAM: streamId=21 errorCode=5
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] INBOUND DATA: streamId=21 padding=0 endStream=false length=8192 bytes=00002430323637633166332d306530392d346135392d613434312d3962363432323261393534620b7a690000004169676c753a636f6d2e736e6f77706c6f7761...
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] OUTBOUND RST_STREAM: streamId=21 errorCode=5
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] INBOUND DATA: streamId=21 padding=0 endStream=false length=8192 bytes=6a736f6e736368656d612f312d302d305c222c5c22646174615c223a7b5c2269645c223a5c2233656336666434382d633637372d346263302d393539342d3166...
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] OUTBOUND RST_STREAM: streamId=21 errorCode=5
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] INBOUND DATA: streamId=21 padding=0 endStream=false length=8192 bytes=2f61727469636c655f636f6e746578742f6a736f6e736368656d612f312d302d305c222c5c22646174615c223a7b5c2261727469636c6549645c223a5c223933...
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] OUTBOUND RST_STREAM: streamId=21 errorCode=5
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] INBOUND DATA: streamId=21 padding=0 endStream=false length=8192 bytes=7465726569207665726769667465743f20446173206572676162656e206469652045726d6974746c756e67656e20646572204b7269706f20526f73656e686569...
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] OUTBOUND RST_STREAM: streamId=21 errorCode=5
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] INBOUND DATA: streamId=21 padding=0 endStream=false length=8192 bytes=2e302e302e30204d6f62696c65205361666172692f3533372e33360b01360000001a68747470733a2f2f7777772e636869656d67617532342e64652f0b014000...
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] OUTBOUND RST_STREAM: streamId=21 errorCode=5
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] INBOUND DATA: streamId=21 padding=0 endStream=false length=8192 bytes=2d466f727761726465642d466f723a2037372e322e3134362e3134362c203133302e3231312e34302e393500000018582d466f727761726465642d50726f746f...
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] OUTBOUND RST_STREAM: streamId=21 errorCode=5
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] INBOUND DATA: streamId=21 padding=0 endStream=false length=8192 bytes=2f000000284163636570742d456e636f64696e673a20677a69702c206465666c6174652c2062722c207a737464000000374163636570742d4c616e6775616765...
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] OUTBOUND RST_STREAM: streamId=21 errorCode=5
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] INBOUND DATA: streamId=21 padding=0 endStream=false length=8192 bytes=3a5c22417274696b656c64657461696c5c222c5c22636f6e74656e74497350617977616c6c5c223a66616c73652c5c22617574686f72735c223a5b5c224d6172...
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] OUTBOUND RST_STREAM: streamId=21 errorCode=5
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] INBOUND DATA: streamId=21 padding=0 endStream=false length=8192 bytes=61653532222c2264756964223a2238356134333764652d353235302d346562322d386439392d643031646537643632376437222c22636f223a227b5c22736368...
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] OUTBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=798268
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] OUTBOUND RST_STREAM: streamId=21 errorCode=5
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] INBOUND DATA: streamId=21 padding=0 endStream=false length=8192 bytes=61223a22746167736a732e7370222c22616964223a22726f73656e6865696d32342e64652d74657374222c2270223a22776562222c22636f6f6b6965223a2231...
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] OUTBOUND RST_STREAM: streamId=21 errorCode=5
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] INBOUND DATA: streamId=21 padding=0 endStream=false length=8192 bytes=6d6979223a2237313335222c2270705f6d6179223a2237373739222c22656964223a2264666264613237312d613732332d346636352d383362312d3763666462...
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] OUTBOUND RST_STREAM: streamId=21 errorCode=5
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] INBOUND DATA: streamId=21 padding=0 endStream=false length=8192 bytes=373b20777629204170706c655765624b69742f3533372e333620284b48544d4c2c206c696b65204765636b6f292056657273696f6e2f342e30204368726f6d65...
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] OUTBOUND RST_STREAM: streamId=21 errorCode=5
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] INBOUND DATA: streamId=21 padding=0 endStream=false length=8192 bytes=7b5c2275736572547970655c223a5c225c222c5c22637561557569645c223a5c2234356365653165332d656664662d326136632d323739372d66303061613338...
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] OUTBOUND RST_STREAM: streamId=21 errorCode=5
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] INBOUND DATA: streamId=21 padding=0 endStream=false length=8192 bytes=322d343533652d623362362d3736353432323332313465340000000f5669613a20312e3120676f6f676c650000002b582d466f727761726465642d466f723a20...
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] OUTBOUND RST_STREAM: streamId=21 errorCode=5
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] INBOUND DATA: streamId=21 padding=0 endStream=false length=8192 bytes=7d7d2c7b5c22736368656d615c223a5c2269676c753a636f6d2e736e6f77706c6f77616e616c79746963732e736e6f77706c6f772f7765625f706167652f6a73...
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] OUTBOUND RST_STREAM: streamId=21 errorCode=5
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] INBOUND DATA: streamId=21 padding=0 endStream=false length=8192 bytes=4e63744c62765f753559325a69493957684a4c4c44352d4a794a4651563541456b77734630524a5579744443797059455534454953452d4d4435465530525112...
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] OUTBOUND RST_STREAM: streamId=21 errorCode=5
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] INBOUND DATA: streamId=21 padding=0 endStream=false length=2766 bytes=4d3242455966437764635848554855517751646e6b30633278614651565254314a5f57466f544257395758463033535a7a79776646585630746245414d435446...
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] OUTBOUND RST_STREAM: streamId=21 errorCode=5
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] INBOUND DATA: streamId=21 padding=0 endStream=false length=8192 bytes=00000036980ac9150ac4014268597358555a495554635a43476852446b3965497a383149436846455145465a304d324245596643776463584855485551775164...
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] OUTBOUND RST_STREAM: streamId=21 errorCode=5
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] INBOUND DATA: streamId=21 padding=0 endStream=false length=5789 bytes=203134372e3136312e3136392e38362c203133302e3231312e34302e393500000018582d466f727761726465642d50726f746f3a20687474707300000016436f...
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x40c23685, L:/10.176.0.140:33530 - R:pubsub.googleapis.com/142.250.181.234:443] OUTBOUND RST_STREAM: streamId=21 errorCode=5
[pool-1-thread-1] INFO enrich.metrics - snowplow.enrich.raw = 0
[pool-1-thread-1] INFO enrich.metrics - snowplow.enrich.good = 0
[pool-1-thread-1] INFO enrich.metrics - snowplow.enrich.bad = 0
[pool-1-thread-1] INFO enrich.metrics - snowplow.enrich.invalid_enriched = 0
```

Keeping the rest of the configuration the same, only downgrading protobuf, results in normal enrichment behaviour.

Let me know if I can provide any additional info or assist in any way.

**Comment by joaolcorreia** [comment]
@jayhof we just released enrich 1.2.2, I'll be doing additional tests with the pubsub enrich and let you know what I find.

**Comment by joaolcorreia** [comment]
hi @jayhof. I launched pub/sub collector and enrich and couldn't replicate but I did found an issue with an enrichment that needs to download some files. I believe that's why the enrich in pub/sub isn't working with referrer enrichment, without it works fine. We can setup a call and review. Im on Slack dbt, locallyOptimistc, measure.

**Comment by kosti-hokkanen-supermetrics** [comment]
Hey just jumping in here and we also noticed similar behavior when trying to upgrade to 1.2.2, it just does not process any messages. Everything seems to be running okay but messages are just not processed.

**Comment by joaolcorreia** [comment]
thank you @kosti-hokkanen-supermetrics ! we're looking into this!

**Comment by joaolcorreia** [comment]
Hi, a status update that we continue looking into this. If we have a solution we'll publish a new version of the enrich and I'll make a note on this issue. Thank you for your patience.

**Comment by joaolcorreia** [comment]
This required extensive changes, but we have a preview version. 
Can you please help us test this and provide feedback?

Docker image:  `docker pull opensnowcat/opensnowcat-enrich-pubsub:1.3.0-preview`

Thank you
